name: retronerd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  flutter_map: ^7.0.2
  gap: ^3.0.1
  google_fonts: ^6.2.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/

  fonts:  
    - family: RetroGaming
      fonts:
        - asset: assets/fonts/RetroGaming.ttf